const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let token=localStorage.getItem('sf_token'), user=null, page='overview', authMode='signup';
const labels={overview:'Overview',products:'Products & stock',customers:'Customers',orders:'Orders & sales',invoices:'Invoices',expenses:'Expenses',assistant:'AI assistant'};
const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n||0));
async function api(path,opts={}){let r=await fetch('/api'+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opts.headers||{})}});let d=await r.json().catch(()=>({detail:'Request failed'}));if(!r.ok)throw Error(d.detail||'Request failed');return d}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showAuth(){ $('#auth').classList.remove('hidden');$('#app').classList.add('hidden'); }
async function boot(){if(!token)return showAuth();try{user=await api('/me');$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#businessName').textContent=user.name+"'s business";$('#profile').textContent=(user.name||'U')[0].toUpperCase();render()}catch(e){localStorage.removeItem('sf_token');token=null;showAuth()}}
$('#toggleAuth').onclick=()=>{authMode=authMode==='signup'?'login':'signup';$('#signupFields').classList.toggle('hidden',authMode==='login');$('#authTitle').textContent=authMode==='signup'?'Turn conversations into customers.':'Welcome back to your business.';$('#authSubmit').innerHTML=authMode==='signup'?'Create free account <span>→</span>':'Sign in <span>→</span>';$('#toggleAuth').textContent=authMode==='signup'?'Sign in':'Create account';$('.switch').firstChild.textContent=authMode==='signup'?'Already have an account? ':'New to SellFlow? '};
$('#authSubmit').onclick=async()=>{try{let body={email:$('#email').value.trim(),password:$('#password').value};if(authMode==='signup')Object.assign(body,{name:$('#name').value.trim()});let d=await api(authMode==='signup'?'/signup':'/login',{method:'POST',body:JSON.stringify(body)});token=d.token;localStorage.setItem('sf_token',token);toast('Welcome to SellFlow AI');boot()}catch(e){toast(e.message)}};
$('#logout').onclick=()=>{localStorage.removeItem('sf_token');token=null;showAuth()};
$('#openSide').onclick=()=>$('#sidebar').classList.add('open');$('#closeSide').onclick=()=>$('#sidebar').classList.remove('open');
$('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(b){page=b.dataset.page;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('open');render()}};
async function render(){ $('#pageCrumb').textContent=labels[page];if(page==='overview')return overview();if(page==='assistant')return assistant();await recordsPage(page)}
function head(title,desc,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${action}</div></div>`}
function stat(title,val,note,icon){return `<div class="stat"><div class="stat-top">${title}<span class="stat-icon">${icon}</span></div><div class="stat-value">${val}</div><div class="stat-note">${note}</div></div>`}
async function overview(){let d=await api('/dashboard'),orders=await api('/orders');let recent=orders.slice(0,4);$('#page').innerHTML=head('Good day, '+esc(user.name.split(' ')[0])+' 👋','Here’s what’s happening with your business today.',`<button class="secondary" onclick="quick('orders')">＋ Add sale</button><button class="primary" onclick="quick('products')">＋ Add product</button>`)+`<div class="stats">${stat('Total revenue',money(d.revenue),'<span class="green">●</span> From paid orders','↗')}${stat('Estimated profit',money(d.profit),'Revenue minus recorded expenses','◈')}${stat('Customers',d.customers,'People in your customer list','♙')}${stat('Pending payments',money(d.pending),'<span class="gold">●</span> Orders & invoices unpaid','◷')}</div><div class="grid2"><div class="panel"><div class="panel-head"><div><h3>Revenue snapshot</h3><div class="panel-sub">Your recorded sales at a glance</div></div><span class="pill">All time</span></div><div class="chart">${[.28,.48,.36,.62,.5,.82,.68,.94].map((h,i)=>`<div class="bar-wrap"><div class="bar" style="height:${h*100}%"></div><span class="bar-label">${['M','T','W','T','F','S','S','↗'][i]}</span></div>`).join('')}</div><div class="panel-sub" style="margin-top:13px">Add paid orders to track real revenue. Bars are a visual placeholder, not historical daily data.</div></div><div class="panel"><div class="panel-head"><div><h3>Recent sales</h3><div class="panel-sub">Your latest orders</div></div><button class="link-btn" onclick="quick('orders')">View all →</button></div>${recent.length?recent.map(o=>`<div class="activity"><div class="activity-icon">▤</div><div class="activity-main"><b>${esc(o.customer||'Customer')}</b><small>${esc(o.item||'Order')} · ${esc(o.created?.slice(0,10)||'Just now')}</small></div><strong>${money(o.total)}</strong></div>`).join(''):`<div class="empty"><div class="empty-icon">▤</div><b>No sales yet</b><p>Add your first order to start tracking revenue.</p><button class="secondary" onclick="quick('orders')">Create an order</button></div>`}</div></div><div class="panel" style="margin-top:2px"><div class="panel-head"><div><h3>Start with the essentials</h3><div class="panel-sub">Build your business workspace in minutes.</div></div></div><div class="actions"><button class="secondary" onclick="quick('products')">▦ Add products</button><button class="secondary" onclick="quick('customers')">♙ Add customers</button><button class="secondary" onclick="quick('invoices')">▧ Create invoice</button><button class="secondary" onclick="quick('assistant')">✧ Ask AI</button></div></div>`}
function quick(p){page=p;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));render()}
const configs={products:{title:'Products & stock',desc:'Keep your catalogue, pricing and stock organized.',fields:[['name','Product name','text'],['sku','SKU / code','text'],['price','Selling price (₦)','number'],['stock','Stock quantity','number']]},customers:{title:'Customers',desc:'Build relationships and keep customer details close.',fields:[['name','Customer name','text'],['email','Email','email'],['phone','Phone / WhatsApp','text'],['notes','Notes','text']]},orders:{title:'Orders & sales',desc:'Record sales and follow payments from one place.',fields:[['customer','Customer','text'],['item','Item / description','text'],['total','Order total (₦)','number'],['status','Payment status','select',['Pending','Paid','Cancelled']]]},invoices:{title:'Invoices',desc:'Create and track invoices for your customers.',fields:[['customer','Customer name','text'],['description','Description','text'],['total','Invoice amount (₦)','number'],['status','Status','select',['Pending','Paid','Overdue']]]},expenses:{title:'Expenses',desc:'Track business costs and understand your profit.',fields:[['description','Expense description','text'],['category','Category','text'],['amount','Amount (₦)','number']]}};
async function recordsPage(kind){let c=configs[kind],rows=await api('/'+kind);let action=`<button class="primary" onclick="openModal('${kind}')">＋ ${kind==='orders'?'Record sale':kind==='invoices'?'New invoice':kind==='expenses'?'Add expense':'Add '+(kind==='products'?'product':'customer')}</button>`;let cols={products:['Product','SKU','Price','Stock'],customers:['Customer','Email','Phone','Added'],orders:['Customer','Item','Total','Status'],invoices:['Customer','Description','Amount','Status'],expenses:['Expense','Category','Amount','Date']}[kind];$('#page').innerHTML=head(c.title,c.desc,action)+`<div class="panel"><div class="panel-head"><div><h3>${rows.length} ${kind}</h3><div class="panel-sub">Your saved business records</div></div><span class="pill">${kind==='orders'?'Sales ledger':'Workspace data'}</span></div>${rows.length?`<div class="table-wrap"><table><thead><tr>${cols.map(x=>`<th>${x}</th>`).join('')}<th></th></tr></thead><tbody>${rows.map(r=>`<tr>${rowCells(kind,r)}<td><button class="row-actions" onclick="removeRecord('${kind}',${r.id})">Delete</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><div class="empty-icon">${kind==='products'?'▦':kind==='customers'?'♙':'▤'}</div><b>No ${kind} yet</b><p>Add your first record. It will be saved to your account.</p><button class="secondary" onclick="openModal('${kind}')">＋ Add ${kind==='orders'?'sale':kind==='invoices'?'invoice':kind==='expenses'?'expense':kind==='products'?'product':'customer'}</button></div>`}</div>`}
function rowCells(k,r){if(k==='products')return `<td><b>${esc(r.name)}</b></td><td>${esc(r.sku||'—')}</td><td>${money(r.price)}</td><td>${esc(r.stock??0)}</td>`;if(k==='customers')return `<td><b>${esc(r.name)}</b></td><td>${esc(r.email||'—')}</td><td>${esc(r.phone||'—')}</td><td>${esc(r.created?.slice(0,10)||'—')}</td>`;if(k==='orders')return `<td><b>${esc(r.customer)}</b></td><td>${esc(r.item)}</td><td>${money(r.total)}</td><td><span class="pill ${r.status==='Paid'?'paid':'pending'}">${esc(r.status||'Pending')}</span></td>`;if(k==='invoices')return `<td><b>${esc(r.customer)}</b></td><td>${esc(r.description)}</td><td>${money(r.total)}</td><td><span class="pill ${r.status==='Paid'?'paid':'pending'}">${esc(r.status||'Pending')}</span></td>`;return `<td><b>${esc(r.description)}</b></td><td>${esc(r.category||'General')}</td><td>${money(r.amount)}</td><td>${esc(r.created?.slice(0,10)||'—')}</td>`}
function openModal(kind){let c=configs[kind];let fields=c.fields.map(([key,label,type,opts])=>`<div class="field"><label>${label}</label>${type==='select'?`<select id="f_${key}">${opts.map(o=>`<option>${o}</option>`).join('')}</select>`:`<input id="f_${key}" type="${type}" ${type==='number'?'min="0" step="any"':''} placeholder="${label}">`}</div>`).join('');let m=document.createElement('div');m.className='modal-back';m.id='modal';m.innerHTML=`<div class="modal"><div class="modal-head"><h2>Add ${kind==='orders'?'sale':kind==='invoices'?'invoice':kind==='expenses'?'expense':kind==='products'?'product':'customer'}</h2><button class="icon-btn" onclick="$('#modal').remove()">×</button></div><form id="recordForm"><div class="form-grid">${fields}</div><div class="modal-actions"><button type="button" class="secondary" onclick="$('#modal').remove()">Cancel</button><button class="primary">Save record</button></div></form></div>`;document.body.append(m);$('#recordForm').onsubmit=async e=>{e.preventDefault();let data={};c.fields.forEach(([key,,type])=>data[key]=type==='number'?Number($('#f_'+key).value||0):$('#f_'+key).value.trim());if(kind==='orders'&&!data.status)data.status='Pending';try{await api('/'+kind,{method:'POST',body:JSON.stringify({data})});$('#modal').remove();toast('Saved successfully');render()}catch(err){toast(err.message)}}}
async function removeRecord(k,id){if(!confirm('Delete this record?'))return;try{await api('/'+k+'/'+id,{method:'DELETE'});toast('Record deleted');render()}catch(e){toast(e.message)}}
async function assistant(){ $('#page').innerHTML=head('AI business assistant','Get practical help with sales, marketing and running your business.')+`<div class="ai-box"><div class="ai-title"><div class="spark">✧</div><div><h3>Your business co-pilot</h3><p>Ask for a sales plan, customer reply, product copy or business advice.</p></div></div><div class="chat-log" id="chat"><div class="bubble bot">Hi ${esc(user.name.split(' ')[0])}! I'm your SellFlow assistant. Tell me what you're working on and I'll help you move it forward.</div></div><form class="chat-form" id="chatForm"><input id="prompt" placeholder="e.g. Write a WhatsApp promo for my sneaker store…" required><button class="primary">Send ↗</button></form><div class="panel-sub" style="margin-top:12px">Live AI requires an OPENAI_API_KEY configured by the site owner. Never paste passwords or payment secrets here.</div></div>`;$('#chatForm').onsubmit=async e=>{e.preventDefault();let q=$('#prompt').value.trim();if(!q)return;let log=$('#chat');log.insertAdjacentHTML('beforeend',`<div class="bubble user">${esc(q)}</div><div class="bubble bot" id="thinking">Thinking…</div>`);$('#prompt').value='';try{let d=await api('/ai',{method:'POST',body:JSON.stringify({message:q})});$('#thinking').textContent=d.reply}catch(err){$('#thinking').textContent=err.message}log.scrollTop=log.scrollHeight}}
boot();
